API/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import NewsAPIView, UserAPIView, AuthorAPIView, CategoryAPIView, CategoryPostAPIView, CategoryUserAPIView
from .yasg import urlpatterns as doc_urls

router = routers.DefaultRouter()
router.register(r'news', NewsAPIView)
router.register(r'categorys', CategoryAPIView)
router.register(r'users', UserAPIView)

router.register(r'authors', AuthorAPIView)
router.register(r'CategoryPost', CategoryPostAPIView)
router.register(r'CategoryUser', CategoryUserAPIView)

app_name = 'API'

urlpatterns = [
    path('submit-data/', include(router.urls)),
]

urlpatterns += doc_urls

Comments/urls.py
from django.urls import path
from .views import CommentsView, comment_accept, comment_del

app_name = 'comments'

urlpatterns = [
    path('', CommentsView.as_view(), name='list'),
    path('<int:pk>/del/', comment_del, name='del'),
    path('<int:pk>/accept/', comment_accept, name='accept'),
]

gamenews_app/urls.py
from .views import NewsView, PostView, PostAddView, PostDelView, PostUpdView, \
    subscrib, unscrib, comment_add_view, comment_del_view, CommentUpdView
from django.contrib.auth.views import LogoutView
from django.urls import path

app_name = 'gnews'

urlpatterns = [
    path('', NewsView.as_view(), name='list'),
    path('<int:pk>/', PostView.as_view(), name='detail'),
    path('add/', PostAddView.as_view(), name='add'),
    path('<int:pk>/del/', PostDelView.as_view(), name='del'),
    path('<int:pk>/edit/', PostUpdView.as_view(), name='upd'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('subscribe/<int:pk>/', subscrib, name='subscribe'),
    path('unscribe/', unscrib, name='unscribe'),
    path('<int:pk>/comment-add/', comment_add_view, name='comment-add'),
    path('comment-del/<int:pk>', comment_del_view, name='comment-del'),
    path('<int:post_pk>/comment-upd/<int:pk>/', CommentUpdView.as_view(), name='comment-upd'),

]

gamenews_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gamenews_app.urls', namespace='gamenews')),
    path('accounts/', include('allauth.urls')),
    path('lk/', include('userprofile.urls', namespace='gn_lk')),
    path('comments/', include('Comments.urls', namespace='comments')),
    path('api/', include('API.urls')),
    path('api/auth/', include('rest_framework.urls', namespace='rest_framework')),

]

userprofile/urls.py
from .views import ProfileView, upgrade_me, DownGrade, profile_edit_view
from django.urls import path

app_name = 'profile'

urlpatterns = [
    path('', ProfileView.as_view(), name='lk'),
    path('upgrade/', upgrade_me, name='upgrade'),
    path('downgrade/', DownGrade.as_view(), name='downgrade'),
    path('edit/', profile_edit_view, name='edit'),
]

templates/profile/lk.html
{% extends "default.html"%}
{% load static%}

{% block title %}
Личный кабинет
{% endblock title %}

{% block main %}
<main class="container container-white" id="main">
    {% endblock main %}

    {% block section %}
    <section class="white-section-100">
        <div class="lk-box">
            <h1 class="h1-white h1-white-margin-b">Личный кабинет</h1>
            <div class=user-data>
                <div class="user-avatar">
                    <img class="user-avatar-img" src="{{ request.user.avatar }}">
                    <nav>
                        <a href="{% url 'profile:edit'%}?action=ava-edit">изменить</a>
                        <a href="{% url 'profile:edit'%}?action=ava-del">удалить</a>
                    </nav>
                </div>

                <div class="user-info">
                    <p><strong>Фамилия</strong>:
                        {{ fname }}
                        <a href="{% url 'profile:edit'%}?action=edit-fname">изменить</a>
                    </p>
                    <p><strong>Имя:</strong>
                        {{ lname }}
                        <a href="{% url 'profile:edit'%}?action=edit-lname">изменить</a>
                    </p>
                    <p><strong>Эл. почта:</strong>
                        {{ request.user.email }}
                        <a href="{% url 'profile:edit'%}?action=edit-email">изменить</a>
                    </p>
                    <p><strong>Псевдоним:</strong>
                        {{ request.user.username }}
                        <a href="{% url 'profile:edit'%}?action=edit-nick">изменить</a>
                    </p>
                    <p class=p-row-action>
          <span class="profile-button">
             <a href="/accounts/password/change/">сменить пароль</a>
              <!--              <a href="#">сменить пароль</a>-->
          </span>
                        <span class="profile-button exit-link">
            <a href="#">Выйти</a>
          </span>
                    </p>

                </div>
            </div>


            <!-- Подписки -->
            <main class="profile-main">
                <div class="subsribtions">
                    <p class="subsribtions-title">Ваши подписки:</p>
                    {% if cats %}
                    <form method="POST" action="{% url 'gnews:unscribe'%}">
                        <input type="hidden" name='action' value="unsubscibe">
                        {% csrf_token %}
                        <ul class="subscriptions-list">
                            {% for cat in cats %}
                            <li>
                                <span>{{ cat.name}} </span>
                                <button class="reuse-btn" type="submit" name="cat_id" value="{{cat.id}}">
                                    отписаться
                                </button>
                            </li>
                            {% endfor %}
                        </ul>
                    </form>
                    {% else %}
                    <p class="subsribtions-title">У вас нет активных подписок</p>
                    {% endif %}
                </div>


                <div class="profile-actions">
                    {% if not is_author %}
                    <p class="profile-button">Для размещения и редактирования новостей нужны авторсие права
                        <a href="{% url 'profile:upgrade' %}"> Получить права</a></p>
                    {% else %}
                    <p class="profile-button"><a href="{% url 'comments:list'%}">МОДЕРИРОВАТЬ КОММЕНТАРИИ
                    </a></p>
                    <p class="profile-button"><a href="{% url 'profile:downgrade' %}">Отказаться от авторских прав</a>
                    </p>
                    {% endif %}
                </div>
            </main>
        </div>


        {% block pagination %}
        {% endblock pagination %}
    </section>
    {% endblock section %}

    {% block aside%}
    {% endblock aside%}

templates/profile/profile-edit.html
{% extends "default.html"%}

{% block title %}
Изменение данных
{% endblock title %}

{% block main %}
<main class="container container-white" id="main">
    {% endblock main %}

    {% block section %}


    <section class="white-section-100">
        <div class="lk-box">

            {% if action == 'ava-edit'%}
            <h1 class="h1-white h1-white-margin-b">Изменение аватара</h1>
            <form class="reuse-form" method='post'>
                {% csrf_token %}
                <div>
                    {% if error %}
                    <span>{{error}}</span><br>
                    {% endif %}
                    <input class="inp" type="url" id="ava" name="ava"
                           placeholder="укажите название ссылки на ваш аватар" size=35>
                    <input class="inp-submit" type="SUBMIT" value="изменить">
                </div>
            </form>
            {% endif %}

            {% if action == 'edit-lname' %}
            <h1 class="h1-white h1-white-margin-b">Изменение фамилии</h1>
            <form class="reuse-form" method='post'>
                {% csrf_token %}
                <div>
                     {% if error %}
                    <span>{{error}}</span><br>
                    {% endif %}
                    <input class="inp" type="text" id="lname" name="lname" placeholder="укажите вашу фамилию">
                    <input class="inp-submit" type="SUBMIT" value="изменить">
                </div>
            </form>
            {% endif %}

            {% if action == 'edit-fname' %}
            <h1 class="h1-white h1-white-margin-b">Изменение имени</h1>
            <form class="reuse-form" method='post'>
                {% csrf_token %}
                <div>
                     {% if error %}
                    <span>{{error}}</span><br>
                    {% endif %}
                    <input class="inp" type="text" id="fname" name="fname" placeholder="укажите ваше имя">
                    <input class="inp-submit" type="SUBMIT" value="изменить">
                </div>
            </form>
            {% endif %}


            {% if action == 'edit-nick' %}
            <h1 class="h1-white h1-white-margin-b">Изменение ника</h1>
            <form class="reuse-form" method='post'>
                {% csrf_token %}
                <div>
                     {% if error %}
                    <span>{{error}}</span><br>
                    {% endif %}
                    <input class="inp" type="text" id="nick" name="nick" placeholder="укажите ваш ник">
                    <input class="inp-submit" type="SUBMIT" value="изменить">
                </div>
            </form>
            {% endif %}


            {% if action == 'edit-email' %}
            <h1 class="h1-white h1-white-margin-b">Изменение email</h1>
            <form class="reuse-form" method='post'>
                {% csrf_token %}
                <div>
                     {% if error %}
                    <span>{{error}}</span><br>
                    {% endif %}
                    <input class="inp" type="email" id="email" name="email" placeholder="укажите ваш email">
                    <input class="inp-submit" type="SUBMIT" value="изменить">
                </div>
            </form>
            <p class="change-profile-attention">После изменения данных понадобится повторно авторизоваться</p>
            {% endif %}


        </div>


    </section>

    {% endblock section %}
    {% block aside %}
    {% endblock aside %}

templates/profile/user-comments.html
{% extends "default.html"%}

comments

{% block title %}
Управление подписками
{% endblock title %}

{% block type_main %}
<main class="container container-white" id="main">
    {% endblock type_main %}


    {% block section %}
    <section class="white-section-100">
        <div class="lk-box">

            <div class="profile-actions">
                <p class="profile-button"><a href="{% url 'profile:lk' %}">В личный кабинет</a></p>
            </div>


            <h1 class="h1-white h1-white-margin-b">Подписки к вашим статьям </h1>


            <!-- Подписки -->
            <div class="profile-main">


            </div>
        </div>
        <br>
        <form method="GET">
            {{ filter.form }}
            <input type="submit" value="Найти">
        </form>
        <br>


        <table>
            <tr>
                <th>Название статьи</th>
                <th>Комментарий</th>
                <th>Пользователь</th>

                <th>Дата и время создания</th>


            </tr>

            {% for comment in comments %}
            <tr>
                <td><a href="{% url 'gnews:detail' comment.post.id %}">{{comment.post.title}}</a></td>
                <td>{{comment.text}}</td>
                <td>{{comment.user}}</td>
                <td>{{comment.date_time|date:"d.m.Y H:i"}}</td>
                <td>
                    <form method="post" action="{% url 'comments:accept' comment.id %}">
                        {% csrf_token %}
                        <button class="reuse-btn" name="comment-id" value="{{comment.id}}">
                            принять
                        </button>
                    </form>
                </td>
                <td>
                    <form method="post" action="{% url 'comments:del' comment.id %}">
                        {% csrf_token %}
                        <button class="reuse-btn-red" name="comment-id" value="{{comment.id}}">
                            удалить
                        </button>
                    </form>
                </td>
            </tr>


            {% endfor %}
        </table>


        {% if is_paginated %}

        <!-- Если доступна предыдущая страница, то даём ссылку на неё и самую первую страницу -->
        {% if page_obj.has_previous %}
        <a href="?page=1">First</a>
        <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
        {% endif %}

        <!-- Показываем только текущую страницу и ближайшие к ней, чтобы список не тянулся и не захламлял страницу -->
        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
        {% endfor %}

        <!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>>></a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

        {% endif %}


        {% block pagination %}
        {% endblock pagination %}


    </section>
    {% endblock section %}

    {% block aside%}
    {% endblock aside%}