API/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import NewsAPIView, UserAPIView, AuthorAPIView, CategoryAPIView, CategoryPostAPIView, CategoryUserAPIView
from .yasg import urlpatterns as doc_urls

router = routers.DefaultRouter()
router.register(r'news', NewsAPIView)
router.register(r'categorys', CategoryAPIView)
router.register(r'users', UserAPIView)

router.register(r'authors', AuthorAPIView)
router.register(r'CategoryPost', CategoryPostAPIView)
router.register(r'CategoryUser', CategoryUserAPIView)

app_name = 'API'

urlpatterns = [
    path('submit-data/', include(router.urls)),
]

urlpatterns += doc_urls

gamenews_app/urls.py
from .views import NewsView, PostView, PostAddView, PostDelView, PostUpdView, \
    subscrib, unscrib, comment_add_view, comment_del_view, CommentUpdView
from django.contrib.auth.views import LogoutView
from django.urls import path

app_name = 'gnews'

urlpatterns = [
    path('', NewsView.as_view(), name='list'),
    path('<int:pk>/', PostView.as_view(), name='detail'),
    path('add/', PostAddView.as_view(), name='add'),
    path('<int:pk>/del/', PostDelView.as_view(), name='del'),
    path('<int:pk>/edit/', PostUpdView.as_view(), name='upd'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('subscribe/<int:pk>/', subscrib, name='subscribe'),
    path('unscribe/', unscrib, name='unscribe'),
    path('<int:pk>/comment-add/', comment_add_view, name='comment-add'),
    path('comment-del/<int:pk>', comment_del_view, name='comment-del'),
    path('<int:post_pk>/comment-upd/<int:pk>/', CommentUpdView.as_view(), name='comment-upd'),

]

gamenews_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gamenews_app.urls', namespace='gamenews')),
    path('accounts/', include('allauth.urls')),
    path('lk/', include('userprofile.urls', namespace='gn_lk')),
    path('comments/', include('Comments.urls', namespace='comments')),
    path('api/', include('API.urls')),
    path('api/auth/', include('rest_framework.urls', namespace='rest_framework')),

]

templates/comment-upd.html
{% extends 'default.html' %}

{% block title %}
Создание статьи
{% endblock %}

{% block main %}
<main class="container container-white" id="main">
    {% endblock %}

    {% block section %}
    <section class="white-section">
        <div id="comments">
            <h1 class="h1-white h1-white-margin-b">
                Изменить ваш комментарий
            </h1>

            <form class="form-post-comment" method="post">
                {% csrf_token%}
                {% for field in form %}
<!--                <label for="{{ field.name}}">{{ field.label}}</label>-->
                {{ field }}
                {% endfor %}
                <img
                        class="comment-avatar avatar"
                        src="{{ request.user.avatar }}"
                        alt="user avatar"
                />
                <div class="comment-actions">
                    <input class="submit-comment" type="submit">
                </div>

            </form>
        </div>
    </section>
    {% endblock section %}

    {% block aside%}
    {% endblock aside %}

templates/post.html
{% extends 'default.html'%}

{% block main %}
<main class="container container-white" id="main">
    {% endblock main %}
    {% block section %}
    <section class="white-section">
        <div class="post">
            <h1 class="h1-postnews-title h1-white">
                <p>
                    {{ post.title }}
                </p>
                {% if request.user.is_authenticated %}
                <nav class="post-actions">
                    <a class="post-actions-link describ-link" href="{% url 'gnews:subscribe' post.id %}">
                        {% if not is_subscriber %}
                        Подписаться
                        {% endif %}
                    </a
                    >


                    <ul class="post-actions-list">
                        {% if is_author%}
                        <li>
                            <a
                                    class="post-actions-link post-actions-link-red"
                                    href="{% url 'gnews:upd' post.id%}"
                            >Редактировать</a
                            >
                        </li>
                        <li>
                            <a
                                    class="post-actions-link post-actions-link-red"
                                    href="{% url 'gnews:del' post.id%}"
                            >Удалить</a
                            >
                        </li>
                        {% endif %}
                        <li>
                            <a class="post-actions-link" href="#comments"
                            >Комментировать</a
                            >
                        </li>
                    </ul>
                </nav>
                {% endif %}
            </h1>
            <div class="post-author-conteiner">
                <p>
                    <span class="post-author-conteiner-label">АВТОР</span>
                    <a class="post-author-conteiner-link" href="#">{{ post.author.user.username}}</a>
                </p>

                <p>
                    <span class="post-author-conteiner-label">ОПУБЛИКОВАНО</span>
                    <span class="post-author-conteiner-content">{{ post.date_time|date:"d.m.Y  h:i" }}</span>
                </p>
                <p>
                    <span class="post-author-conteiner-label">КОММЕНТАРИИ</span>
                    <span class="post-author-conteiner-content">{{ post.count_comments }}</span>
                </p>
            </div>
            <img
                    class="post-main-img"
                    src="{{post.main_img}}"
                    alt="POST big Img"
            />
            <div class="post-box">
                {% for row in post_text %}
                <p class="post-text">
                    {{ row }}
                </p>
                {% endfor %}
            </div>

        </div>
        <div id="comments">

            {% block comments-form%}
            {% if request.user.is_authenticated %}

            <form class="form-post-comment" method="post" action="{% url 'gnews:comment-add' post.id%}">

                <textarea
                        name = 'text'
                        class="input-post-comment"
                        placeholder="Введите ваше сообщение"
                ></textarea>
                <img
                        class="comment-avatar avatar"
                        src="{{ request.user.avatar }}"
                        alt="user avatar"
                />
                <div class="comment-actions">
                    <input class="submit-comment" type="submit">
                </div>
                {% csrf_token%}
            </form>
            {% endif %}
            {% endblock comments-form %}

            {% for comment in comments%}
            <div class="post-comment" id="comment-{{comment.id}}">
                <p class="comment-user-nick">
                    {{comment.user}} <span>{{ comment.date_time|date:"d.m.Y  h:i" }}</span>
                </p>
                <img
                        class="avatar comment-avatar"
                        src="{{ comment.user.avatar }}"
                        alt="user avatar"
                />

                <p class="comment-text">
                    {{ comment.text }}
                </p>
                {% if request.user == comment.user %}
                <nav>
                     <a href="{% url 'gnews:comment-upd' post.id comment.id %}">редактировать</a>
                    <a href="{% url 'gnews:comment-del' comment.id%}">удалить</a>
                </nav>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </section>
    {% endblock section %}

</main>

templates/post_add.html
{% extends 'default.html' %}

{% block title %}
Создание статьи
{% endblock %}

{% block main %}
<main class="container container-white" id="main">
    {% endblock %}

    {% block section %}
    <section class="white-section">
        <div class="forms-box">
            <h1 class="h1-white h1-white-margin-b">
                Разместить статью
            </h1>
            <form class="reuse-form" action="" method="post">
                {% csrf_token%}
                {{ form }}
                <input class="inp-submit" type = 'submit' value="разместить">
            </form>
        </div>
    </section>
    {% endblock section %}

    {% block aside%}
    {% endblock aside %}

templates/post_del.html
{% extends "default.html"%}
{% load static%}

{% block title %}
Games Portal Статья
{% endblock title %}

{% block main %}
<main class="container container-white" id="main">
    {% endblock main %}

    {% block section %}
    <section class="white-section-100">
        <div class="forms-box">
            <h1 class="h1-white h1-white-margin-b">
                Внимание!!! Данная новость будет удалена !!!
            </h1>
            <h2>
                <form method="post">
                    {% csrf_token%}
                    {{form}}
                    <input class="inp-submit" type="submit" value="удалить">
                </form>
            </h2>
        </div>

    </section>
    {% endblock section %}

    {% block aside %}
    {% endblock aside %}